import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// ページのメタデータ
export const metadata = {
  title: "Next.js Awesome Memo App",
  description: "Generated by create next app",
};

// ページのレイアウト
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      {/* ページやレイアウトの内容を表示 */}
      <body>{children}</body>
    </html>
  );
}
